name: pdf_plus
description: Pdf creation library for dart
homepage: https://github.com/insinfo/pdf_plus
repository: https://github.com/insinfo/pdf_plus

version: 3.13.0

environment:
  sdk: ^3.6.0

dependencies:
  archive: ">=3.4.0 <4.1.0"  
  image: ">=4.1.0 <=5.0.0"
  meta: ">=1.3.0 <2.0.0"
   
dev_dependencies:
  test: ^1.26.3  
  path: ^1.9.1  
