name: pdf_plus
description: Pdf creation library for dart
homepage: https://github.com/insinfo/pdf_plus
repository: https://github.com/insinfo/pdf_plus

version: 3.12.0

environment:
  sdk: ^3.6.0

dependencies:
  archive: ">=3.4.0 <4.1.0" 
  collection: ^1.19.1
  convert: ^3.1.2
  crypto: ^3.0.7 
  image: ">=4.1.0 <=5.0.0"
  meta: ">=1.3.0 <2.0.0"
  #path_parsing: ">=0.2.0 <2.0.0"  
  #vector_math: ^2.2.0 
  #xml: ">=6.3.0 <7.0.0"
   # barcode: ">=2.2.3 <3.0.0"
  # bidi: ^2.0.10

dev_dependencies:
  test: ^1.26.3  
  path: ^1.9.1
  
